import type { StylePreset } from '@/types'

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'pop',
    nameKey: 'input.style.pop',
    descriptionKey: 'input.style.pop',
    defaultBpm: 120,
    defaultKey: 'C',
  },
  {
    id: 'classical',
    nameKey: 'input.style.classical',
    descriptionKey: 'input.style.classical',
    defaultBpm: 100,
    defaultKey: 'C',
  },
  {
    id: 'electronic',
    nameKey: 'input.style.electronic',
    descriptionKey: 'input.style.electronic',
    defaultBpm: 128,
    defaultKey: 'Am',
  },
  {
    id: 'jazz',
    nameKey: 'input.style.jazz',
    descriptionKey: 'input.style.jazz',
    defaultBpm: 90,
    defaultKey: 'F',
  },
  {
    id: 'rock',
    nameKey: 'input.style.rock',
    descriptionKey: 'input.style.rock',
    defaultBpm: 140,
    defaultKey: 'E',
  },
  {
    id: 'lofi',
    nameKey: 'input.style.lofi',
    descriptionKey: 'input.style.lofi',
    defaultBpm: 80,
    defaultKey: 'Am',
  },
  {
    id: 'ambient',
    nameKey: 'input.style.ambient',
    descriptionKey: 'input.style.ambient',
    defaultBpm: 60,
    defaultKey: 'C',
  },
  {
    id: 'metal',
    nameKey: 'input.style.metal',
    descriptionKey: 'input.style.metal',
    defaultBpm: 160,
    defaultKey: 'Em',
  },
  {
    id: 'country',
    nameKey: 'input.style.country',
    descriptionKey: 'input.style.country',
    defaultBpm: 110,
    defaultKey: 'G',
  },
  {
    id: 'reggae',
    nameKey: 'input.style.reggae',
    descriptionKey: 'input.style.reggae',
    defaultBpm: 75,
    defaultKey: 'Am',
  },
  {
    id: 'rnb',
    nameKey: 'input.style.rnb',
    descriptionKey: 'input.style.rnb',
    defaultBpm: 85,
    defaultKey: 'Cm',
  },
  {
    id: 'funk',
    nameKey: 'input.style.funk',
    descriptionKey: 'input.style.funk',
    defaultBpm: 105,
    defaultKey: 'E',
  },
  {
    id: 'cinematic',
    nameKey: 'input.style.cinematic',
    descriptionKey: 'input.style.cinematic',
    defaultBpm: 70,
    defaultKey: 'Dm',
  },
]
